/*
PowerDNS Authoritative HTTP API

Testing AutoprimaryAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/argonaut0/pdns-client-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_AutoprimaryAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AutoprimaryAPIService CreateAutoprimary", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var serverId string

		httpRes, err := apiClient.AutoprimaryAPI.CreateAutoprimary(context.Background(), serverId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AutoprimaryAPIService DeleteAutoprimary", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var serverId string
		var ip string
		var nameserver string

		httpRes, err := apiClient.AutoprimaryAPI.DeleteAutoprimary(context.Background(), serverId, ip, nameserver).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AutoprimaryAPIService GetAutoprimaries", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var serverId string

		resp, httpRes, err := apiClient.AutoprimaryAPI.GetAutoprimaries(context.Background(), serverId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
