/*
PowerDNS Authoritative HTTP API

Testing ZonecryptokeyAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/argonaut0/pdns-client-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_ZonecryptokeyAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ZonecryptokeyAPIService CreateCryptokey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var serverId string
		var zoneId string

		resp, httpRes, err := apiClient.ZonecryptokeyAPI.CreateCryptokey(context.Background(), serverId, zoneId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ZonecryptokeyAPIService DeleteCryptokey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var serverId string
		var zoneId string
		var cryptokeyId string

		httpRes, err := apiClient.ZonecryptokeyAPI.DeleteCryptokey(context.Background(), serverId, zoneId, cryptokeyId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ZonecryptokeyAPIService GetCryptokey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var serverId string
		var zoneId string
		var cryptokeyId string

		resp, httpRes, err := apiClient.ZonecryptokeyAPI.GetCryptokey(context.Background(), serverId, zoneId, cryptokeyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ZonecryptokeyAPIService ListCryptokeys", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var serverId string
		var zoneId string

		resp, httpRes, err := apiClient.ZonecryptokeyAPI.ListCryptokeys(context.Background(), serverId, zoneId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ZonecryptokeyAPIService ModifyCryptokey", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var serverId string
		var zoneId string
		var cryptokeyId string

		httpRes, err := apiClient.ZonecryptokeyAPI.ModifyCryptokey(context.Background(), serverId, zoneId, cryptokeyId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
