/*
PowerDNS Authoritative HTTP API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.15
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MapStatisticItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MapStatisticItem{}

// MapStatisticItem struct for MapStatisticItem
type MapStatisticItem struct {
	// Item name
	Name *string `json:"name,omitempty"`
	// Set to \"MapStatisticItem\"
	Type *string `json:"type,omitempty"`
	// Named values
	Value []SimpleStatisticItem `json:"value,omitempty"`
}

// NewMapStatisticItem instantiates a new MapStatisticItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMapStatisticItem() *MapStatisticItem {
	this := MapStatisticItem{}
	return &this
}

// NewMapStatisticItemWithDefaults instantiates a new MapStatisticItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMapStatisticItemWithDefaults() *MapStatisticItem {
	this := MapStatisticItem{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *MapStatisticItem) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MapStatisticItem) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *MapStatisticItem) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *MapStatisticItem) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *MapStatisticItem) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MapStatisticItem) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *MapStatisticItem) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *MapStatisticItem) SetType(v string) {
	o.Type = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *MapStatisticItem) GetValue() []SimpleStatisticItem {
	if o == nil || IsNil(o.Value) {
		var ret []SimpleStatisticItem
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MapStatisticItem) GetValueOk() ([]SimpleStatisticItem, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *MapStatisticItem) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given []SimpleStatisticItem and assigns it to the Value field.
func (o *MapStatisticItem) SetValue(v []SimpleStatisticItem) {
	o.Value = v
}

func (o MapStatisticItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MapStatisticItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableMapStatisticItem struct {
	value *MapStatisticItem
	isSet bool
}

func (v NullableMapStatisticItem) Get() *MapStatisticItem {
	return v.value
}

func (v *NullableMapStatisticItem) Set(val *MapStatisticItem) {
	v.value = val
	v.isSet = true
}

func (v NullableMapStatisticItem) IsSet() bool {
	return v.isSet
}

func (v *NullableMapStatisticItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMapStatisticItem(val *MapStatisticItem) *NullableMapStatisticItem {
	return &NullableMapStatisticItem{value: val, isSet: true}
}

func (v NullableMapStatisticItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMapStatisticItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


